name: "Arek Stryjski"
description: "Informacje na temat planowanych rejsów morskich, relacje z poprzednich rejsów, porady żeglarskie."
url: "http://stryjski.net"
lang: pl
encoding: UTF-8
permalink: /:title/
exclude: [arekstryjski.github.io.iml, README.md, res, dist, bin]
