name: "Arek Stryjski"
description: "żeglarstwo, rejsy, jachty, sailing, cruising, yachts"
url: "http://stryjski.net"
lang: pl
encoding: UTF-8
permalink: /:categories/:title/
exclude: [arekstryjski.github.io.iml, README.md, res]
#markdown: rdiscount
#rdiscount:
#  extensions:
#    - autolink      # greedily urlify links
#    - footnotes     # footnotes
#    - smart         # typographic substitutions with SmartyPants
