name: "Arek Stryjski"
description: "żeglarstwo, rejsy, jachty, sailing, cruising, yachts"

url: "http://stryjski.com"

paginate: 10

markdown: rdiscount
permalink: pretty

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
